server:
  port: 7003

spring:
  application:
    name: comment-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/mydb?characterEncoding=UTF-8
    username: mydbid
    password: mydbpw

  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #      settings:
  #        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

shop:
  message: E-shop